version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: military
      MYSQL_USER: rooot
      MYSQL_PASSWORD: password
    volumes:
      - ./1military/db:/docker-entrypoint-initdb.d  # Mount database initialization scripts
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306

  # PHP service
  php:
    image: mudocker001/envi
    volumes:
      - ./:/var/www/html  # Mount project directory
    ports:
      - "80:80"  # Map container port 80 to host port 80

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    volumes:
      - ./:/usr/share/nginx/html  # Mount project directory
    depends_on:
      - php  # Depend on PHP service
