version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: military
      MYSQL_USER: rooot
      MYSQL_PASSWORD: password
    volumes:
      - ./1military/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8001:80"
    networks:
      - app-network

  php:
    image: mudocker001/envi
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"  # Changed to avoid conflict if 80 is already in use on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html  # Nginx uses /usr/share/nginx/html by default
    depends_on:
      - php  # Depend on the PHP service which likely serves as the 'web' service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: {}